version: '3'

services:
  web:
    container_name: web_app_autoglaze
    image: node
    command: sh -c "npm install && npx prisma migrate dev --name init && npm run dev"
    env_file: ".env"
    restart: always
    environment:
      DATABASE_URL: "mysql://root:$MYSQL_ROOT_PASSWORD@db/$MYSQL_DATABASE"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network_app_autoglaze

  db:
    image: mariadb:latest
    container_name: db_app_autoglaze
    command: --default-authentication-plugin=mysql_native_password
    env_file: ".env"
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - network_app_autoglaze
    volumes:
      - dbcont:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin_app_autoglaze
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - network_app_autoglaze
    depends_on:
      - db

networks:
  network_app_autoglaze:
    driver: bridge
    name: network_app_autoglaze

volumes:
  .:
    name: web_app_autoglaze_volume
  dbcont:
    name: db_app_autoglaze_volume